package coyotos;

/**
 * @brief Application-defined interrupt posting interface
 */
interface AppInt extends Cap {
  /// @brief Post application-defined interrupt @p intr to the application. 
  ///
  /// Raises NoAccess if this capability does not permit posting of the
  /// requested interrupt.
  ///
  /// Raises NoAccess if the endpoint directly named by this capability contains
  /// Null capability in its recipient slot.
  void postInterrupt(unsigned long intr) raises(NoAccess);
};
