package coyotos;

/// @brief Low-level interrupt control capability.
///
/// An IrqCtl capability provides the authority to allocate IrqWait
/// capabilities.  wait on one of a range of interrupts. The invoker
/// calls waitForInterrupt, which returns when the requested interrupt
/// becomes in service. The IrqRange capability describes a range of
/// interrupts that the wielder can wait for. A given process can wait
/// for only one interrupt at a time.

interface IrqWait extends Cap {
  /// @brief Disable a given hardware interrupt line.
  void disable();

  /// @brief Enable a given hardware interrupt line.
  void enable();

  /// @brief Wait for an interrupt to occur on a given hardware
  /// interrupt line.
  void wait();
};

