/*****************************************************************
 * DO NOT EDIT - MACHINE-GENERATED FILE!
 * 
 * Source file : simple.idl
 * Platform    : X0 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.0.2 (roadrunner) on 02/08/2007 11:33
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#if !defined(__simple_client_h__)
#define __simple_client_h__

#define IDL4_OMIT_FRAME_POINTER 0
#define IDL4_USE_FASTCALL 0
#define IDL4_NEED_MALLOC 1
#define IDL4_API x0
#define IDL4_ARCH ia32

#include "idl4/idl4.h"

#if IDL4_HEADER_REVISION < 20030403
#error You are using outdated versions of the IDL4 header files
#endif /* IDL4_HEADER_REVISION < 20030403 */

/* Interface simple */

#if !defined(_objdef___simple)
#define _objdef___simple
typedef CORBA_Object simple;
#endif /* !defined(_objdef___simple) */

// Channel 0:                        ID SIZE ALGN FLAGS PRIO CIDX COFS SIDX SOFS
//   D0: l4_fpage_t _rcv_window       3    4    4 c----    0    0    0   -2   -8
//   D1: idl4_msgdope_t _size_dope    4    4    4 c----    0    1    4   -1   -4
//   D2: idl4_msgdope_t _send_dope    5    4    4 c----    0    2    8    0    0
//   D-: int _esp                     9    4    4 -s--p    0   -1   -1   -2   -8
//   D-: int _ebp                     A    4    4 -s--p    0   -1   -1   -1   -4
//   D-: l4_threadid_t _caller        B    4    4 ----p    0   -1   -1   -1   -1
//   R0: CORBA_long parameter         2    4    4 c-fx-    5    0   12    0   12
//   R2: int __fid                    0    4    4 csfxp    9    2   20    2   20
// 
//   Send dope: 0x6000                     Size dope: 0x6000
// 
// Channel 1:                        ID SIZE ALGN FLAGS PRIO CIDX COFS SIDX SOFS
//   D0: l4_fpage_t _rcv_window       6    4    4 c----    0    0    0   -2   16
//   D1: idl4_msgdope_t _size_dope    7    4    4 c----    0    1    4   -1   20
//   D2: idl4_msgdope_t _send_dope    8    4    4 c----    0    2    8    0   24
//   R2: int __eid                    0    4    4 csfxp    9    2   20    2   44
// 
//   Send dope: 0x6000
// 
// Client buffer:                |
//   IN:  ------------2222----0000
//   OUT: --------------------0000
// 
// Server buffer:                |
//   IN:  --------------------0000
//   OUT: --------------------------------------------0000

#if !defined(_funcdef___simple_foo)
#define _funcdef___simple_foo
static inline void simple_foo(simple _service, const CORBA_long parameter, CORBA_Environment *_env)

{
  int _exception;
  idl4_msgdope_t _msgDope;

  /* invoke IPC */
  
  __asm__ __volatile__(
    "push %%ebp                         \n\t"
    "xor %%ebp, %%ebp                   \n\t"
    "xor %%eax, %%eax                   \n\t"
    "int $0x30                          \n\t"
    : 
    : "d" ((unsigned int)parameter), "D" ((unsigned int)0), "S" (_service), "c" ((_env == 0) ? L4_IPC_NEVER : _env->_timeout)
    : "cc", "memory"
  );

  __asm__ __volatile__(
    "pop %%ebp                          \n\t"
    : "=D" (_exception), "=a" (_msgDope)
    : 
    : "edx", "ebx", "ecx", "esi"
  );

  if (_env != 0)
    __asm__ __volatile__(
      "andl $0xF0, %%eax                  \n\t"
      "shl $4, %%eax                      \n\t"
      "setnz %%al                         \n\t"
      "cmovz %%edi, %%eax                 \n\t"
      : "=a" (*(int*)_env)
      : "a" (_msgDope), "D" (_exception)
    );
}
#endif /* !defined(_funcdef___simple_foo) */

#endif /* !defined(__simple_client_h__) */
