/*****************************************************************
 * Source file : simple.idl
 * Platform    : X0 IA32
 * Mapping     : CORBA C
 * 
 * Generated by IDL4 1.0.2 (roadrunner) on 02/08/2007 11:34
 * Report bugs to haeberlen@ira.uka.de
 *****************************************************************/

#include "simple_template_server.h"

/* Interface simple */

IDL4_INLINE void simple_foo_implementation(CORBA_Object _caller, const CORBA_long parameter, idl4_server_environment *_env)

{
  /* implementation of simple::foo */
  
  return;
}

IDL4_PUBLISH_SIMPLE_FOO(simple_foo_implementation);

void *simple_vtable[SIMPLE_DEFAULT_VTABLE_SIZE] = SIMPLE_DEFAULT_VTABLE;

void simple_server(void)

{
  unsigned int msgdope, dummy, fnr, reply, w0, w1, w2;
  l4_threadid_t partner;
  struct {
    unsigned int stack[768];
    l4_fpage_t rcv_window;
    unsigned int size_dope;
    unsigned int send_dope;
    unsigned int message[SIMPLE_MSGBUF_SIZE];
    idl4_strdope_t str[SIMPLE_STRBUF_SIZE];
  } buffer;

  while (1)
    {
      buffer.size_dope = SIMPLE_RCV_DOPE;
      buffer.rcv_window = idl4_nilpage;
      partner = idl4_nilthread;
      reply = idl4_nil;
      w0 = w1 = w2 = 0;

      while (1)
        {
          idl4_reply_and_wait(reply, buffer, partner, msgdope, fnr, w0, w1, w2, dummy);

          if (msgdope & 0xF0)
            break;

          idl4_process_request(simple_vtable, fnr & SIMPLE_FID_MASK, reply, buffer, partner, w0, w1, w2, dummy);
        }

      enter_kdebug("message error");
    }
}

void simple_discard(void)

{
}

